### ISSUE TITLE
Worth mentioning Cario dependency

### ISSUE THREAD

**Issue by hughrawlinson** [michaelrhodes/get-image-data#4]
I ran `npm install --save get-image-data` and node-gyp complained that I didn't have cairo installed. I haven't checked but I guess it's either a dependency of this project, or a dependency of a dependency of this project. It's worth noting in the Readme that it's required.

**Comment by michaelrhodes** [comment]
Good point, I’m thinking of making canvas a peer dependency in the package.json because native dependencies are a pain when you’re only installing for the browser variant. Obviously a note in the README would follow, but does that sound good to you?

**Comment by hughrawlinson** [comment]
Yep, that sounds great to me :)

**Comment by michaelrhodes** [comment]
Sweet, it’s a peer dependency as of 3.0.0. I updated the README accordingly—Idon’t mention the Cairo dependency explicitly, but it’s alluded to in my disclaimer, so hopefully that’ll do. Thanks for the help :)
