### ISSUE TITLE
does not load from remote image

### ISSUE THREAD

**Issue by nobuttsseb** [michaelrhodes/get-image-data#5]
Here is the runkit example: https://runkit.com/nobuttsseb/5a37895f998e5a00115cacc0

Is there something I am missing here? Or can only local files be used?

**Comment by michaelrhodes** [comment]
Unfortunately only local files and buffers can used as input for get-image, on which this module depends. That said I wasn’t even able to get your example working by requesting the image and using the response buffer as input—hoping that’s just something to do with RunKit and not mah modules
